{{- range $p := .Values.ipAddressPools }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ $p.name }}
  namespace: {{ $p.namespace }}
spec:
  addresses:
  {{- range $addr := $p.addresses }}
  - {{ $addr }}
  {{- end }}
{{- end }}
