{{- range $a := .Values.l2Advertisements }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ $a.name }}
  namespace: {{ $a.namespace }}
spec:
  {{- if $a.ipAddressPools }}
  ipAddressPools:
  {{- range $pool := $a.ipAddressPools }}
  - {{ $pool }}
  {{- end }}
  {{- end }}
{{- end }}
