{{- range $sg := .Values.serviceGroups }}
---
apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: {{ $sg.name }}
  namespace: {{ $sg.namespace }}
spec:
  local:
    v4pools:
    {{- range $pool := $sg.v4pools }}
    - subnet: {{ $pool.subnet }}
      pool: {{ $pool.pool }}/{{ .pool_cidr | default "32" }}
      aggregation: {{ $pool.aggregation | default "default" }}
    {{- end }}
    v6pools:
    {{- range $pool := $sg.v6pools }}
    - subnet: {{ $pool.subnet }}
      pool: {{ $pool.pool }}/{{ .pool_cidr | default "32" }}
      aggregation: {{ $pool.aggregation | default "default" }}
    {{- end }}
{{- end }}
