#issuers:
#- name: letsencrypt-prod
#  kind: ClusterIssuer
#  spec:
#    acme:
#      email: bob@example.com
#      server: https://acme-v02.api.letsencrypt.org/directory
#      privateKeySecretRef:
#        name: letsencrypt-prod
#      solvers:
#      - dns01:
#          cloudflare:
#            email: bob@example.com
#            apiTokenSecretRef:
#              name: cloudflare-api-token
#              key: api-token
#        selector: {}
