apiVersion: v1
kind: Service
metadata:
  name: {{ include "bind9.fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "bind9.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 4 }}
  selector:
    {{- include "bind9.selectorLabels" . | nindent 4 }}
