apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tftp.fullname" . }}
  labels:
    {{- include "tftp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tftp.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tftp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tftp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range $svc, $v := .Values.services }}
          {{- range $port := $v.ports }}
          - name: {{ $svc }}
            containerPort: {{ $port.containerPort | default $port.port }}
            protocol: {{ $port.protocol }}
          {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 2
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 2
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: assets
            mountPath: /assets
          - name: configmenus
            mountPath: /config/menus
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: assets
        {{- if (.Values.persistence.assets).enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.assets.existingClaim | default (print (include "tftp.fullname" $) "-assets") }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: configmenus
        {{- if (.Values.persistence.configmenus).enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.configmenus.existingClaim | default (print (include "tftp.fullname" $) "-configmenus") }}
        {{- else }}
        emptyDir: {}
        {{- end }}
