{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tftp.fullname" $ }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "tftp.labels" $ | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  ports:
  {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "tftp.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
