{{- range $svc,$v := .Values.services }}
{{- if $v.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tftp.fullname" $ }}-{{ $svc }}
{{- if $v.annotations }}
  annotations:
{{ toYaml $v.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "tftp.labels" $ | nindent 4 }}
{{- if $v.labels }}
{{ toYaml $v.labels | nindent 4 }}
{{- end }}
spec:
  type: {{ $v.type }}
{{- if $v.loadBalancerIP }}
  loadBalancerIP: {{ $v.loadBalancerIP }}
{{- end }}
  ports:
  {{- toYaml $v.ports | nindent 4 }}
  selector:
    {{- include "tftp.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
