apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adguardhome.fullname" . }}
  labels:
    {{- include "adguardhome.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "adguardhome.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "adguardhome.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "adguardhome.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: dns-tcp
              containerPort: 5353
              protocol: TCP
            - name: dns-udp
              containerPort: 5353
              protocol: UDP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: web-init
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: work
            mountPath: /opt/adguardhome/work
          - name: conf
            mountPath: /opt/adguardhome/conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: work
        {{- if .Values.persistence.work.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.work.existingClaim | default (print (include "adguardhome.fullname" $) "-work") }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: conf
        {{- if .Values.persistence.conf.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.conf.existingClaim | default (print (include "adguardhome.fullname" $) "-conf") }}
        {{- else }}
        emptyDir: {}
        {{- end }}
