{{- range $k,$v := .Values.volumes }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
 name: {{ include "pv.fullname" $ }}-{{ $k }}
 labels:
   {{- include "pv.labels" $ | nindent 4 }}
spec:
{{- toYaml $v.spec | nindent 2 }}
{{- end }}
