apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keadhcp.fullname" . }}
  labels:
    {{- include "keadhcp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keadhcp.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        checksum/configmap-config: {{ include (print $.Template.BasePath "/configmap-dhcp.yaml") $ | sha256sum }}
        checksum/configmap-ctrl-agent: {{ include (print $.Template.BasePath "/configmap-ctrl-agent.yaml") $ | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keadhcp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keadhcp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ "-c", "/kea/config/dhcp4.json" ]
          ports:
            - name: dhcp-udp
              containerPort: 67
              protocol: UDP
          readinessProbe:
            exec:
              command:
              - pgrep
              - kea-dhcp4
            periodSeconds: 10
            initialDelaySeconds: 2
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
              - pgrep
              - kea-dhcp4
            periodSeconds: 10
            initialDelaySeconds: 2
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            capabilities:
              add:
              - NET_RAW
          volumeMounts:
          - name: config
            mountPath: /kea/config
          - name: leases
            mountPath: /kea/leases
          - name: sockets
            mountPath: /kea/sockets
        - name: ctrl-agent
          image: "{{ .Values.ctrl_agent_image.repository }}:{{ .Values.ctrl_agent_image.tag | default .Chart.AppVersion }}"
          args: [ "-c", "/kea/config/config.json" ]
          volumeMounts:
          - name: probe
            mountPath: /probe
          - name: sockets
            mountPath: /kea/sockets
          - name: ctrl-agent-config
            mountPath: /kea/config
          readinessProbe:
            exec:
              command:
              - /usr/bin/python3
              - /probe/probe.py
            periodSeconds: 10
            initialDelaySeconds: 2
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
              - /usr/bin/python3
              - /probe/probe.py
            periodSeconds: 10
            initialDelaySeconds: 2
            timeoutSeconds: 5
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "keadhcp.fullname" . }}
      - name: leases
        {{- if .Values.persistence.leases.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.leases.existingClaim | default (print (include "keadhcp.fullname" $) "-leases") }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: sockets
        emptyDir: {}
      - name: ctrl-agent-config
        configMap:
          name: {{ include "keadhcp.fullname" . }}-ctrl-agent
      - name: probe
        configMap:
          name: {{ include "keadhcp.fullname" . }}-probe
