---
#l2Advertisements:
#- name: testadv
#  namespace: metallb
#  spec:
#    ipAddressPools:
#    - first-pool

#ipAddressPools:
#- name: first-pool
#  namespace: metallb
#  spec:
#    addresses:
#    - 1.1.1.1
#    - 2.2.2.2
#    - 3.3.3.3
