---
#l2Advertisements:
#- name: testadv
#  namespace: metallb
#  ipAddressPools:
#  - first-pool

#ipAddressPools:
#- name: first-pool
#  namespace: metallb
#  addresses:
#  - 1.1.1.1
#  - 2.2.2.2
#  - 3.3.3.3
